/**: 
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: map #global_costmap/costmap
    costmap_updates_topic: map_updates #global_costmap/costmap_updates
    visualize: true
    planner_frequency: 0.15 #1.0 
    progress_timeout: 50.0 # Tempo massimo senza progresso prima di considerare una frontiera fallita
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.3
    min_frontier_size: 0.75 