# Set the base image of the container to ROS 2 Jazzy
FROM ros:jazzy
# Install the turtlesim package (simple graphical environment for testing ROS) and all its components.
RUN apt update -y && apt install ros-jazzy-turtlesim* -y
# Install rqt_graph, a graphical tool for viewing the ROS node and connection graph.
RUN apt update -y && apt install -y ros-jazzy-rqt-graph
# Install the basic tools 
RUN apt update -y && apt install -y \
    wget \
    ros-jazzy-urdf-tutorial \
    liburdfdom-tools \
    # Install gazebo
    ros-jazzy-ros-gz \
    # Install navigation stuff
    ros-jazzy-navigation2 ros-jazzy-nav2-bringup \
    python3-colcon-common-extensions

# Set the default working directory within the container to /root/ros_workspace
WORKDIR /root/ros_workspace

# Library associated with explore lite 
RUN apt update -y && apt install -y ros-jazzy-image-geometry

# Bookstores for YOLO
RUN apt update -y && apt install -y python3-pip ros-jazzy-cv-bridge
RUN pip install --break-system-packages --no-deps ultralytics 
RUN pip install --break-system-packages torch torchvision polars
